version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"

conda:
  environment: doc/environment.yml

sphinx:
  # Path to your Sphinx configuration file.
  configuration: doc/conf.py