{% set data = load_setup_py_data() %}

package:
  name: openalea.hydroshoot
  version: {{ data.get('version') }}


source:
  git_url: ../

build:
  noarch: python
  preserve_egg_dir: True
  script: {{PYTHON}} setup.py install

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - sympy
    - pandas
    - jsonschema
    - pvlib-python
    - openalea.mtg
    - openalea.plantgl
    - alinea.caribu
    - alinea.astk

about:
  summary: "HydroShoot is an FSPM model to simulate gas-exchange on vine"
  license: "cecill-c"
  license_file: LICENSE
